- name: Play common roles
  ansible.builtin.include_role:
    name: "{{ item }}"
  loop:
    - users
    - sudoers
    - bash-profile
    - chrony
    - hostname
    - locale
    - timezone
    - inputrc
    - devsec.hardening.ssh_hardening
  tags: ['common']
